import { describe, it, expect } from 'vitest';
import {
  getRecurringSummary,
  detectPendingRecurring,
  getCandidateDatesForMonth,
  getNormalizedMonthlyAmount,
  clampDayToMonth,
} from '../recurring';
import { AppState, ExpenseItem, IncomeItem } from '../../types/finance';

const baseState = (over: Partial<AppState> = {}): AppState => ({
  selectedMonth: '2026-09',
  budgetConfig: { needsPercent: 50, wantsPercent: 30, savingsDebtPercent: 20, categoryBudgets: {} as any },
  incomes: [],
  expenses: [],
  savingsGoals: [],
  debts: [],
  netWorthItems: [],
  monthlyReviewNotes: {},
  ...over,
});

const income = (over: Partial<IncomeItem> = {}): IncomeItem => ({
  id: 'i1',
  source: 'Salary',
  amount: 100000,
  date: '2026-09-01',
  createdAt: '',
  ...over,
});

const expense = (over: Partial<ExpenseItem> = {}): ExpenseItem => ({
  id: 'e1',
  category: 'Rent/Housing',
  type: 'Essential',
  amount: 50000,
  date: '2026-09-02',
  createdAt: '',
  ...over,
});

describe('getNormalizedMonthlyAmount', () => {
  it('scales weekly up and yearly down', () => {
    expect(getNormalizedMonthlyAmount(1000, 'weekly')).toBe(4333);
    expect(getNormalizedMonthlyAmount(1000, 'monthly')).toBe(1000);
    expect(getNormalizedMonthlyAmount(12000, 'yearly')).toBe(1000);
  });
});

describe('clampDayToMonth', () => {
  it('clamps a 31st to a short month', () => {
    expect(clampDayToMonth('2026-02', 31)).toBe(28);
    expect(clampDayToMonth('2026-04', 31)).toBe(30);
    expect(clampDayToMonth('2026-01', 15)).toBe(15);
  });

  it('handles a leap February', () => {
    expect(clampDayToMonth('2028-02', 31)).toBe(29);
  });
});

describe('getCandidateDatesForMonth', () => {
  it('produces one date per month for a monthly rule', () => {
    expect(getCandidateDatesForMonth('2026-09-02', 'monthly', '2026-10')).toEqual(['2026-10-02']);
  });

  it('only fires a yearly rule in its anniversary month', () => {
    expect(getCandidateDatesForMonth('2026-09-02', 'yearly', '2026-10')).toEqual([]);
    expect(getCandidateDatesForMonth('2026-09-02', 'yearly', '2027-09')).toEqual(['2027-09-02']);
  });

  it('produces every matching weekday for a weekly rule', () => {
    const dates = getCandidateDatesForMonth('2026-09-02', 'weekly', '2026-10');
    expect(dates.length).toBeGreaterThanOrEqual(4);
    expect(dates.length).toBeLessThanOrEqual(5);
    // 2026-09-02 is a Wednesday; every result must also be a Wednesday
    for (const d of dates) {
      const [y, m, day] = d.split('-').map(Number);
      expect(new Date(y, m - 1, day).getDay()).toBe(3);
    }
  });
});

describe('getRecurringSummary', () => {
  it('counts source templates only, so the baseline does not inflate after generation', () => {
    const template = income({ id: 'i1', isRecurring: true, recurringFrequency: 'monthly' });
    const generated = income({
      id: 'i2',
      date: '2026-10-01',
      isRecurring: true,
      recurringFrequency: 'monthly',
      autoGeneratedFromId: 'i1',
    });

    const before = getRecurringSummary([template], []);
    const after = getRecurringSummary([template, generated], []);

    expect(before.monthlyRecIncome).toBe(100000);
    expect(before.recurringIncomeCount).toBe(1);
    // Regression: generated instances previously counted as rules of their own.
    expect(after.monthlyRecIncome).toBe(100000);
    expect(after.recurringIncomeCount).toBe(1);
  });

  it('ignores non-recurring records', () => {
    const summary = getRecurringSummary([income()], [expense()]);
    expect(summary.recurringIncomeCount).toBe(0);
    expect(summary.recurringExpenseCount).toBe(0);
    expect(summary.netRecurringFlow).toBe(0);
  });
});

describe('detectPendingRecurring', () => {
  it('proposes a monthly rule once for the target month', () => {
    const state = baseState({
      expenses: [expense({ isRecurring: true, recurringFrequency: 'monthly' })],
    });
    const pending = detectPendingRecurring(state, '2026-10');
    expect(pending.pendingExpenses).toHaveLength(1);
    expect(pending.pendingExpenses[0].date).toBe('2026-10-02');
    expect(pending.pendingExpenses[0].autoGeneratedFromId).toBe('e1');
  });

  it('does not re-propose the template into its own month', () => {
    const state = baseState({
      expenses: [expense({ isRecurring: true, recurringFrequency: 'monthly' })],
    });
    expect(detectPendingRecurring(state, '2026-09').totalCount).toBe(0);
  });

  it('does not duplicate an entry that was already generated', () => {
    const template = expense({ isRecurring: true, recurringFrequency: 'monthly' });
    const generated = expense({ id: 'e2', date: '2026-10-02', autoGeneratedFromId: 'e1' });
    const state = baseState({ expenses: [template, generated] });
    expect(detectPendingRecurring(state, '2026-10').totalCount).toBe(0);
  });

  it('does not duplicate an entry the user already recorded by hand', () => {
    const template = expense({ isRecurring: true, recurringFrequency: 'monthly' });
    const manual = expense({ id: 'manual', date: '2026-10-02' });
    const state = baseState({ expenses: [template, manual] });
    expect(detectPendingRecurring(state, '2026-10').totalCount).toBe(0);
  });

  it('treats a generated instance as an instance, never as a new rule', () => {
    const generated = expense({
      id: 'e2',
      date: '2026-09-02',
      isRecurring: true,
      recurringFrequency: 'monthly',
      autoGeneratedFromId: 'e1',
    });
    const state = baseState({ expenses: [generated] });
    expect(detectPendingRecurring(state, '2026-10').totalCount).toBe(0);
  });

  it('expands a weekly rule into every matching week', () => {
    const state = baseState({
      expenses: [expense({ amount: 4000, isRecurring: true, recurringFrequency: 'weekly' })],
    });
    const pending = detectPendingRecurring(state, '2026-10');
    expect(pending.pendingExpenses.length).toBeGreaterThanOrEqual(4);
    for (const e of pending.pendingExpenses) expect(e.amount).toBe(4000);
  });
});
