export type IncomeSource = 'Salary' | 'Freelance' | 'Business' | 'Rental' | 'Investment' | 'Other';

export type RecurringFrequency = 'weekly' | 'monthly' | 'yearly';

export interface IncomeItem {
  id: string;
  source: IncomeSource;
  amount: number;
  date: string; // YYYY-MM-DD
  notes?: string;
  createdAt: string;
  isRecurring?: boolean;
  recurringFrequency?: RecurringFrequency;
  autoGeneratedFromId?: string;
}

export type ExpenseCategory =
  | 'Food'
  | 'Medicine'
  | 'Rent/Housing'
  | 'Utilities'
  | 'Transport'
  | 'Work'
  | 'Insurance'
  | 'Education'
  | 'Family'
  | 'Shopping'
  | 'Entertainment'
  | 'Other';

export type ExpenseType = 'Essential' | 'Want';

export interface ExpenseItem {
  id: string;
  category: ExpenseCategory;
  type: ExpenseType; // Essential (Need) vs Want
  amount: number;
  date: string; // YYYY-MM-DD
  notes?: string;
  createdAt: string;
  isRecurring?: boolean;
  recurringFrequency?: RecurringFrequency;
  autoGeneratedFromId?: string;
}

export interface CategoryBudget {
  category: ExpenseCategory;
  limit: number;
}

export interface BudgetConfig {
  needsPercent: number; // default 50
  wantsPercent: number; // default 30
  savingsDebtPercent: number; // default 20
  categoryBudgets: Record<ExpenseCategory, number>;
}

export interface SavingsGoal {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  deadline: string; // YYYY-MM-DD
  isEmergencyFund?: boolean;
  notes?: string;
  createdAt: string;
}

export interface DebtPayment {
  id: string;
  amount: number;
  date: string;
  notes?: string;
}

export interface DebtItem {
  id: string;
  creditor: string;
  originalAmount: number;
  remainingAmount: number;
  interestRate: number; // Annual interest %
  minimumPayment: number;
  dueDate: string; // Day of month or specific date
  notes?: string;
  paymentHistory: DebtPayment[];
  createdAt: string;
}

export type AssetCategory =
  | 'Cash'
  | 'Bank accounts'
  | 'Investments'
  | 'Property'
  | 'Gold/Silver'
  | 'Other assets';

export type LiabilityCategory =
  | 'Loans'
  | 'Credit cards'
  | 'Other debts';

export interface NetWorthItem {
  id: string;
  name: string;
  type: 'asset' | 'liability';
  category: AssetCategory | LiabilityCategory;
  amount: number;
  notes?: string;
  updatedAt: string;
}

export interface StressFactor {
  name: string;
  status: 'safe' | 'warning' | 'danger';
  value: string;
  description: string;
}

export interface FinancialStressMetrics {
  score: number; // 0 (Peaceful/Calm) to 100 (Severe Stress)
  level: 'Calm' | 'Low' | 'Moderate' | 'High' | 'Severe';
  incomeVsExpensesRatio: number;
  debtToIncomeRatio: number;
  emergencyFundMonths: number;
  overspendingCount: number;
  liquidCash: number;
  recommendations: string[];
  factors: StressFactor[];
  practicalActions: string[];
}

export type TabType =
  | 'dashboard'
  | 'income'
  | 'expense'
  | 'recurring'
  | 'budget'
  | 'savings'
  | 'debt'
  | 'networth'
  | 'stress'
  | 'review'
  | 'coach'
  | 'islamic';

export interface AppState {
  incomes: IncomeItem[];
  expenses: ExpenseItem[];
  budgetConfig: BudgetConfig;
  savingsGoals: SavingsGoal[];
  debts: DebtItem[];
  netWorthItems: NetWorthItem[];
  selectedMonth: string; // YYYY-MM
  theme: 'light' | 'dark';
  monthlyReviewNotes: Record<string, string>;
}
