import React, { useState, useMemo } from 'react';
import {
  Calendar as CalendarIcon,
  ChevronLeft,
  ChevronRight,
  Zap,
  Repeat,
  CheckCircle2,
  AlertCircle,
  Filter,
  Search,
  Download,
  Trash2,
  Info,
  List,
  Grid,
  TrendingUp,
  TrendingDown,
  Layers,
  Clock,
  X,
  ArrowRight,
  ShieldCheck,
  CalendarCheck,
} from 'lucide-react';
import { AppState, IncomeItem, ExpenseItem, RecurringFrequency } from '../types/finance';
import { formatPKR, formatMonthName, formatDate, exportToCSV } from '../utils/formatters';
import { detectPendingRecurring, getDaysInMonth } from '../utils/recurring';

interface RecurringAutomationTabProps {
  state: AppState;
  onProcessRecurring?: (targetMonth: string) => void;
  onDeleteIncome?: (id: string) => void;
  onDeleteExpense?: (id: string) => void;
  onNavigateToIncome?: () => void;
  onNavigateToExpense?: () => void;
}

export type AutomationItemType = 'income' | 'expense';
export type AutomationStatus = 'auto-generated' | 'template-rule' | 'pending-scheduled';

export interface UnifiedAutomationEntry {
  id: string;
  type: AutomationItemType;
  title: string;
  categoryOrSource: string;
  amount: number;
  date: string; // YYYY-MM-DD
  frequency: RecurringFrequency;
  status: AutomationStatus;
  notes?: string;
  createdAt?: string;
  autoGeneratedFromId?: string;
  sourceTemplateId?: string;
  rawIncome?: IncomeItem;
  rawExpense?: ExpenseItem;
}

export const RecurringAutomationTab: React.FC<RecurringAutomationTabProps> = ({
  state,
  onProcessRecurring,
  onDeleteIncome,
  onDeleteExpense,
  onNavigateToIncome,
  onNavigateToExpense,
}) => {
  // Navigation month state (defaults to state.selectedMonth)
  const [currentMonth, setCurrentMonth] = useState<string>(state.selectedMonth);
  const [viewMode, setViewMode] = useState<'calendar' | 'audit'>('calendar');
  const [filterType, setFilterType] = useState<'all' | 'income' | 'expense'>('all');
  const [filterStatus, setFilterStatus] = useState<'all' | 'auto-generated' | 'template-rule' | 'pending-scheduled'>('all');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [selectedEntry, setSelectedEntry] = useState<UnifiedAutomationEntry | null>(null);
  const [selectedDateDetails, setSelectedDateDetails] = useState<string | null>(null);
  const [actionFeedback, setActionFeedback] = useState<string | null>(null);

  // Sync if state.selectedMonth changes
  React.useEffect(() => {
    setCurrentMonth(state.selectedMonth);
  }, [state.selectedMonth]);

  // Navigate months
  const handlePrevMonth = () => {
    const [year, month] = currentMonth.split('-').map(Number);
    const prevDate = new Date(year, month - 2, 1);
    const newMonth = `${prevDate.getFullYear()}-${String(prevDate.getMonth() + 1).padStart(2, '0')}`;
    setCurrentMonth(newMonth);
  };

  const handleNextMonth = () => {
    const [year, month] = currentMonth.split('-').map(Number);
    const nextDate = new Date(year, month, 1);
    const newMonth = `${nextDate.getFullYear()}-${String(nextDate.getMonth() + 1).padStart(2, '0')}`;
    setCurrentMonth(newMonth);
  };

  const handleResetToCurrentMonth = () => {
    setCurrentMonth(state.selectedMonth);
  };

  // Find all pending recurring items for this current month
  const pendingRecurring = useMemo(() => {
    return detectPendingRecurring(state, currentMonth);
  }, [state, currentMonth]);

  // Extract all unified entries for current month
  const monthEntries = useMemo(() => {
    const list: UnifiedAutomationEntry[] = [];

    // 1. Processed or registered Incomes for this month
    state.incomes.forEach((inc) => {
      if (!inc.date.startsWith(currentMonth)) return;

      const isAutoGenerated = Boolean(inc.autoGeneratedFromId || inc.id.startsWith('inc_rec_'));
      const isTemplateRule = Boolean(inc.isRecurring && !inc.autoGeneratedFromId && !inc.id.startsWith('inc_rec_'));

      if (isAutoGenerated || isTemplateRule) {
        list.push({
          id: inc.id,
          type: 'income',
          title: inc.source,
          categoryOrSource: inc.source,
          amount: inc.amount,
          date: inc.date,
          frequency: inc.recurringFrequency || 'monthly',
          status: isAutoGenerated ? 'auto-generated' : 'template-rule',
          notes: inc.notes,
          createdAt: inc.createdAt,
          autoGeneratedFromId: inc.autoGeneratedFromId,
          sourceTemplateId: inc.autoGeneratedFromId,
          rawIncome: inc,
        });
      }
    });

    // 2. Processed or registered Expenses for this month
    state.expenses.forEach((exp) => {
      if (!exp.date.startsWith(currentMonth)) return;

      const isAutoGenerated = Boolean(exp.autoGeneratedFromId || exp.id.startsWith('exp_rec_'));
      const isTemplateRule = Boolean(exp.isRecurring && !exp.autoGeneratedFromId && !exp.id.startsWith('exp_rec_'));

      if (isAutoGenerated || isTemplateRule) {
        list.push({
          id: exp.id,
          type: 'expense',
          title: exp.category,
          categoryOrSource: exp.category,
          amount: exp.amount,
          date: exp.date,
          frequency: exp.recurringFrequency || 'monthly',
          status: isAutoGenerated ? 'auto-generated' : 'template-rule',
          notes: exp.notes,
          createdAt: exp.createdAt,
          autoGeneratedFromId: exp.autoGeneratedFromId,
          sourceTemplateId: exp.autoGeneratedFromId,
          rawExpense: exp,
        });
      }
    });

    // 3. Pending scheduled items for this month (detected by recurring engine)
    pendingRecurring.pendingIncomes.forEach((p, idx) => {
      list.push({
        id: `pending-inc-${idx}-${p.sourceTemplateId}-${p.date}`,
        type: 'income',
        title: p.source,
        categoryOrSource: p.source,
        amount: p.amount,
        date: p.date,
        frequency: p.recurringFrequency || 'monthly',
        status: 'pending-scheduled',
        notes: p.notes,
        sourceTemplateId: p.sourceTemplateId,
      });
    });

    pendingRecurring.pendingExpenses.forEach((p, idx) => {
      list.push({
        id: `pending-exp-${idx}-${p.sourceTemplateId}-${p.date}`,
        type: 'expense',
        title: p.category,
        categoryOrSource: p.category,
        amount: p.amount,
        date: p.date,
        frequency: p.recurringFrequency || 'monthly',
        status: 'pending-scheduled',
        notes: p.notes,
        sourceTemplateId: p.sourceTemplateId,
      });
    });

    // Sort by date ascending
    return list.sort((a, b) => a.date.localeCompare(b.date));
  }, [state.incomes, state.expenses, currentMonth, pendingRecurring]);

  // Filtered entries
  const filteredEntries = useMemo(() => {
    return monthEntries.filter((item) => {
      // Type filter
      if (filterType !== 'all' && item.type !== filterType) return false;
      // Status filter
      if (filterStatus !== 'all' && item.status !== filterStatus) return false;
      // Search query
      if (searchQuery.trim()) {
        const query = searchQuery.toLowerCase();
        const matchTitle = item.title.toLowerCase().includes(query);
        const matchCategory = item.categoryOrSource.toLowerCase().includes(query);
        const matchNotes = item.notes?.toLowerCase().includes(query);
        if (!matchTitle && !matchCategory && !matchNotes) return false;
      }
      return true;
    });
  }, [monthEntries, filterType, filterStatus, searchQuery]);

  // Aggregate monthly stats for the view
  const stats = useMemo(() => {
    const processedIncomes = monthEntries.filter(
      (e) => e.type === 'income' && (e.status === 'auto-generated' || e.status === 'template-rule')
    );
    const processedExpenses = monthEntries.filter(
      (e) => e.type === 'expense' && (e.status === 'auto-generated' || e.status === 'template-rule')
    );

    const totalIncome = processedIncomes.reduce((sum, i) => sum + i.amount, 0);
    const totalExpense = processedExpenses.reduce((sum, e) => sum + e.amount, 0);

    const autoGeneratedCount = monthEntries.filter((e) => e.status === 'auto-generated').length;
    const templateRuleCount = monthEntries.filter((e) => e.status === 'template-rule').length;
    const pendingCount = monthEntries.filter((e) => e.status === 'pending-scheduled').length;

    return {
      totalIncome,
      totalExpense,
      netFlow: totalIncome - totalExpense,
      incomeCount: processedIncomes.length,
      expenseCount: processedExpenses.length,
      autoGeneratedCount,
      templateRuleCount,
      pendingCount,
    };
  }, [monthEntries]);

  // Days mapping for calendar grid
  const calendarDays = useMemo(() => {
    const [year, month] = currentMonth.split('-').map(Number);
    const daysCount = getDaysInMonth(currentMonth);
    const firstDayIndex = new Date(year, month - 1, 1).getDay(); // 0 is Sunday

    // Days in previous month to pad first row
    const prevMonthLastDate = new Date(year, month - 1, 0).getDate();

    const days: Array<{
      dateString: string;
      dayNumber: number;
      isCurrentMonth: boolean;
      isToday: boolean;
      entries: UnifiedAutomationEntry[];
    }> = [];

    const todayStr = new Date().toISOString().slice(0, 10);

    // Leading padding days from previous month
    for (let i = firstDayIndex - 1; i >= 0; i--) {
      const dNum = prevMonthLastDate - i;
      const prevM = month - 1 === 0 ? 12 : month - 1;
      const prevY = month - 1 === 0 ? year - 1 : year;
      const dStr = `${prevY}-${String(prevM).padStart(2, '0')}-${String(dNum).padStart(2, '0')}`;
      days.push({
        dateString: dStr,
        dayNumber: dNum,
        isCurrentMonth: false,
        isToday: dStr === todayStr,
        entries: [],
      });
    }

    // Days of the current month
    for (let d = 1; d <= daysCount; d++) {
      const dStr = `${currentMonth}-${String(d).padStart(2, '0')}`;
      const dayEntries = filteredEntries.filter((e) => e.date === dStr);
      days.push({
        dateString: dStr,
        dayNumber: d,
        isCurrentMonth: true,
        isToday: dStr === todayStr,
        entries: dayEntries,
      });
    }

    // Trailing padding days to fill 7 columns
    const remainingSlots = (7 - (days.length % 7)) % 7;
    for (let i = 1; i <= remainingSlots; i++) {
      const nextM = month + 1 === 13 ? 1 : month + 1;
      const nextY = month + 1 === 13 ? year + 1 : year;
      const dStr = `${nextY}-${String(nextM).padStart(2, '0')}-${String(i).padStart(2, '0')}`;
      days.push({
        dateString: dStr,
        dayNumber: i,
        isCurrentMonth: false,
        isToday: dStr === todayStr,
        entries: [],
      });
    }

    return days;
  }, [currentMonth, filteredEntries]);

  // Execute processing of pending recurring entries
  const handleRunProcessing = () => {
    if (onProcessRecurring) {
      onProcessRecurring(currentMonth);
      setActionFeedback(`Successfully processed and populated ${stats.pendingCount} recurring entries for ${formatMonthName(currentMonth)}.`);
      setTimeout(() => setActionFeedback(null), 4000);
    }
  };

  // Delete automated entry
  const handleDeleteEntry = (entry: UnifiedAutomationEntry) => {
    if (entry.status === 'pending-scheduled') {
      setSelectedEntry(null);
      return;
    }

    if (entry.type === 'income' && onDeleteIncome) {
      onDeleteIncome(entry.id);
      setSelectedEntry(null);
      setActionFeedback(`Automated income "${entry.title}" (${formatPKR(entry.amount)}) removed from records.`);
      setTimeout(() => setActionFeedback(null), 4000);
    } else if (entry.type === 'expense' && onDeleteExpense) {
      onDeleteExpense(entry.id);
      setSelectedEntry(null);
      setActionFeedback(`Automated expense "${entry.title}" (${formatPKR(entry.amount)}) removed from records.`);
      setTimeout(() => setActionFeedback(null), 4000);
    }
  };

  // Export to CSV
  const handleExportCSV = () => {
    const headers = [
      'Date',
      'Type',
      'Source/Category',
      'Amount (PKR)',
      'Automation Status',
      'Frequency',
      'Source Template ID',
      'Processed Timestamp',
      'Notes',
    ];

    const rows = filteredEntries.map((e) => [
      e.date,
      e.type === 'income' ? 'Income' : 'Expense',
      e.categoryOrSource,
      e.amount,
      e.status === 'auto-generated'
        ? 'Auto-Processed'
        : e.status === 'template-rule'
        ? 'Base Rule Template'
        : 'Scheduled Pending',
      e.frequency,
      e.sourceTemplateId || e.autoGeneratedFromId || 'N/A',
      e.createdAt ? new Date(e.createdAt).toLocaleString() : 'N/A',
      e.notes || '',
    ]);

    exportToCSV(`recurring-automation-history-${currentMonth}.csv`, [headers, ...rows]);
  };

  // Find entries for a clicked date
  const dateEntriesForModal = useMemo(() => {
    if (!selectedDateDetails) return [];
    return filteredEntries.filter((e) => e.date === selectedDateDetails);
  }, [selectedDateDetails, filteredEntries]);

  return (
    <div className="space-y-6">
      {/* Toast Feedback */}
      {actionFeedback && (
        <div className="fixed top-5 right-5 z-50 flex items-center gap-2 rounded-xl border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-900 shadow-lg dark:border-emerald-700 dark:bg-emerald-950 dark:text-emerald-100 animate-in fade-in slide-in-from-top-2">
          <CheckCircle2 className="h-5 w-5 text-emerald-600 shrink-0" />
          <span>{actionFeedback}</span>
          <button
            onClick={() => setActionFeedback(null)}
            className="ml-2 text-emerald-700 hover:text-emerald-900 dark:text-emerald-300"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      )}

      {/* Header Bar */}
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs dark:border-slate-800 dark:bg-slate-900">
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
          <div>
            <div className="flex items-center gap-2.5">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-600 text-white shadow-sm shadow-indigo-500/20">
                <Repeat className="h-5 w-5" />
              </div>
              <div>
                <h1 className="text-xl font-bold tracking-tight text-slate-900 dark:text-white flex items-center gap-2">
                  <span>Recurring Automation Calendar</span>
                  <span className="rounded-full bg-indigo-100 dark:bg-indigo-950/80 px-2.5 py-0.5 text-xs font-semibold text-indigo-800 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800">
                    Audit & Verification
                  </span>
                </h1>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                  Calendar-style visual history of all automatically processed income and expense entries
                </p>
              </div>
            </div>
          </div>

          {/* Month Controls & Actions */}
          <div className="flex flex-wrap items-center gap-2 sm:gap-3">
            {/* Month Navigator */}
            <div className="flex items-center rounded-xl border border-slate-200 bg-slate-50 p-1 dark:border-slate-700 dark:bg-slate-800 text-slate-700 dark:text-slate-200">
              <button
                onClick={handlePrevMonth}
                className="rounded-lg p-1.5 hover:bg-white dark:hover:bg-slate-700 transition"
                title="Previous Month"
                aria-label="Previous Month"
              >
                <ChevronLeft className="h-4 w-4" />
              </button>
              <div className="px-3 text-xs font-bold whitespace-nowrap min-w-[130px] text-center">
                {formatMonthName(currentMonth)}
              </div>
              <button
                onClick={handleNextMonth}
                className="rounded-lg p-1.5 hover:bg-white dark:hover:bg-slate-700 transition"
                title="Next Month"
                aria-label="Next Month"
              >
                <ChevronRight className="h-4 w-4" />
              </button>
            </div>

            {/* Today Button */}
            {currentMonth !== state.selectedMonth && (
              <button
                onClick={handleResetToCurrentMonth}
                className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300 transition"
              >
                Current Month
              </button>
            )}

            {/* View Mode Toggle */}
            <div className="flex rounded-xl border border-slate-200 bg-slate-50 p-1 dark:border-slate-700 dark:bg-slate-800">
              <button
                onClick={() => setViewMode('calendar')}
                className={`flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-semibold transition ${
                  viewMode === 'calendar'
                    ? 'bg-white text-indigo-600 shadow-xs dark:bg-slate-900 dark:text-indigo-400'
                    : 'text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-200'
                }`}
                title="Calendar Grid View"
              >
                <Grid className="h-3.5 w-3.5" />
                <span className="hidden sm:inline">Calendar</span>
              </button>
              <button
                onClick={() => setViewMode('audit')}
                className={`flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-semibold transition ${
                  viewMode === 'audit'
                    ? 'bg-white text-indigo-600 shadow-xs dark:bg-slate-900 dark:text-indigo-400'
                    : 'text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-200'
                }`}
                title="Audit Log Table View"
              >
                <List className="h-3.5 w-3.5" />
                <span className="hidden sm:inline">Audit Log</span>
              </button>
            </div>

            {/* Export CSV */}
            <button
              onClick={handleExportCSV}
              className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200 transition"
              title="Export Month's Automation Entries to CSV"
            >
              <Download className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Export CSV</span>
            </button>

            {/* Process Pending Button */}
            {stats.pendingCount > 0 && onProcessRecurring && (
              <button
                onClick={handleRunProcessing}
                className="inline-flex items-center gap-1.5 rounded-xl bg-indigo-600 px-3.5 py-2 text-xs font-semibold text-white shadow-sm hover:bg-indigo-700 transition"
              >
                <Zap className="h-3.5 w-3.5" />
                <span>Process {stats.pendingCount} Pending</span>
              </button>
            )}
          </div>
        </div>

        {/* Quick Pending Alert if applicable */}
        {stats.pendingCount > 0 && (
          <div className="mt-4 rounded-xl border border-indigo-200 bg-indigo-50/80 p-3.5 dark:border-indigo-800/60 dark:bg-indigo-950/40 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div className="flex items-center gap-2.5">
              <Clock className="h-4 w-4 text-indigo-600 dark:text-indigo-400 shrink-0" />
              <span className="text-xs text-indigo-950 dark:text-indigo-200">
                <strong>{stats.pendingCount} recurring transactions</strong> are scheduled for{' '}
                {formatMonthName(currentMonth)} but have not yet been populated into your financial records.
              </span>
            </div>
            {onProcessRecurring && (
              <button
                onClick={handleRunProcessing}
                className="inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-indigo-700 transition shrink-0"
              >
                <Zap className="h-3 w-3" />
                Auto-Populate for {formatMonthName(currentMonth)}
              </button>
            )}
          </div>
        )}
      </div>

      {/* KPI Overview Cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {/* Automated Inflows */}
        <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-xs dark:border-slate-800 dark:bg-slate-900">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-500 dark:text-slate-400">
              Automated Inflows
            </span>
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-50 text-emerald-600 dark:bg-emerald-950 dark:text-emerald-400">
              <TrendingUp className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-2 text-xl font-bold tracking-tight text-emerald-600 dark:text-emerald-400">
            {formatPKR(stats.totalIncome)}
          </div>
          <p className="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
            {stats.incomeCount} automated income {stats.incomeCount === 1 ? 'entry' : 'entries'} verified
          </p>
        </div>

        {/* Automated Outflows */}
        <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-xs dark:border-slate-800 dark:bg-slate-900">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-500 dark:text-slate-400">
              Automated Outflows
            </span>
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-rose-50 text-rose-600 dark:bg-rose-950 dark:text-rose-400">
              <TrendingDown className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-2 text-xl font-bold tracking-tight text-rose-600 dark:text-rose-400">
            {formatPKR(stats.totalExpense)}
          </div>
          <p className="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
            {stats.expenseCount} automated bill {stats.expenseCount === 1 ? 'entry' : 'entries'} verified
          </p>
        </div>

        {/* Net Automated Flow */}
        <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-xs dark:border-slate-800 dark:bg-slate-900">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-500 dark:text-slate-400">
              Net Automated Flow
            </span>
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-400">
              <Layers className="h-4 w-4" />
            </div>
          </div>
          <div
            className={`mt-2 text-xl font-bold tracking-tight ${
              stats.netFlow >= 0
                ? 'text-emerald-600 dark:text-emerald-400'
                : 'text-rose-600 dark:text-rose-400'
            }`}
          >
            {formatPKR(stats.netFlow)}
          </div>
          <p className="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
            {stats.netFlow >= 0 ? 'Net surplus via automation' : 'Net automated deficit'}
          </p>
        </div>

        {/* Processing Verification Status */}
        <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-xs dark:border-slate-800 dark:bg-slate-900">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-500 dark:text-slate-400">
              Automation Health
            </span>
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-400">
              <ShieldCheck className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-2 text-xl font-bold tracking-tight text-slate-900 dark:text-white flex items-center gap-1.5">
            <span>{stats.autoGeneratedCount + stats.templateRuleCount}</span>
            <span className="text-xs font-normal text-slate-400">Processed</span>
          </div>
          <p className="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
            {stats.pendingCount > 0 ? (
              <span className="text-amber-600 dark:text-amber-400 font-medium">
                {stats.pendingCount} pending generation
              </span>
            ) : (
              <span className="text-emerald-600 dark:text-emerald-400 font-medium">
                All rules verified & populated
              </span>
            )}
          </p>
        </div>
      </div>

      {/* Filter and Search Toolbar */}
      <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-xs dark:border-slate-800 dark:bg-slate-900">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
          {/* Left: Type and Status Pills */}
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-xs font-medium text-slate-400 flex items-center gap-1">
              <Filter className="h-3 w-3" />
              Filter:
            </span>

            {/* Type Filter */}
            <div className="flex rounded-lg border border-slate-200 bg-slate-50 p-0.5 dark:border-slate-700 dark:bg-slate-800 text-xs">
              <button
                onClick={() => setFilterType('all')}
                className={`rounded-md px-2.5 py-1 font-medium transition ${
                  filterType === 'all'
                    ? 'bg-white text-slate-900 shadow-xs dark:bg-slate-900 dark:text-white'
                    : 'text-slate-600 hover:text-slate-900 dark:text-slate-400'
                }`}
              >
                All ({monthEntries.length})
              </button>
              <button
                onClick={() => setFilterType('income')}
                className={`rounded-md px-2.5 py-1 font-medium transition ${
                  filterType === 'income'
                    ? 'bg-emerald-600 text-white shadow-xs'
                    : 'text-slate-600 hover:text-slate-900 dark:text-slate-400'
                }`}
              >
                Income Only
              </button>
              <button
                onClick={() => setFilterType('expense')}
                className={`rounded-md px-2.5 py-1 font-medium transition ${
                  filterType === 'expense'
                    ? 'bg-rose-600 text-white shadow-xs'
                    : 'text-slate-600 hover:text-slate-900 dark:text-slate-400'
                }`}
              >
                Expenses Only
              </button>
            </div>

            {/* Status Filter */}
            <select
              value={filterStatus}
              onChange={(e) => setFilterStatus(e.target.value as any)}
              className="rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-medium text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200 focus:outline-none cursor-pointer"
            >
              <option value="all">All Statuses</option>
              <option value="auto-generated">⚡ Auto-Generated by Engine</option>
              <option value="template-rule">📋 Base Recurring Rules</option>
              <option value="pending-scheduled">⏳ Scheduled Pending</option>
            </select>
          </div>

          {/* Right: Search box */}
          <div className="relative w-full md:w-64">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400" />
            <input
              type="text"
              placeholder="Search automated entry..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full rounded-lg border border-slate-200 bg-slate-50 pl-8 pr-3 py-1.5 text-xs text-slate-900 placeholder-slate-400 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100 focus:outline-none focus:ring-1 focus:ring-indigo-500"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
              >
                <X className="h-3 w-3" />
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Main View: Calendar Grid Mode */}
      {viewMode === 'calendar' && (
        <div className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5 shadow-xs dark:border-slate-800 dark:bg-slate-900">
          {/* Calendar Header Legend */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-4 border-b border-slate-100 dark:border-slate-800 gap-3">
            <div className="flex items-center gap-2">
              <CalendarCheck className="h-4 w-4 text-indigo-600 dark:text-indigo-400" />
              <h2 className="text-sm font-bold text-slate-900 dark:text-white">
                Monthly Schedule & Processing Grid ({formatMonthName(currentMonth)})
              </h2>
            </div>
            {/* Visual Legend */}
            <div className="flex flex-wrap items-center gap-3 text-[11px] text-slate-500 dark:text-slate-400">
              <div className="flex items-center gap-1.5">
                <span className="h-2.5 w-2.5 rounded-full bg-emerald-500" />
                <span>Auto Income</span>
              </div>
              <div className="flex items-center gap-1.5">
                <span className="h-2.5 w-2.5 rounded-full bg-rose-500" />
                <span>Auto Expense</span>
              </div>
              <div className="flex items-center gap-1.5">
                <span className="h-2.5 w-2.5 rounded-full border border-dashed border-indigo-400 bg-indigo-50 dark:bg-indigo-950" />
                <span>Scheduled / Pending</span>
              </div>
              <div className="flex items-center gap-1.5">
                <span className="flex h-3.5 w-3.5 items-center justify-center rounded-full bg-indigo-600 text-[8px] font-bold text-white">
                  ⚡
                </span>
                <span>Auto-Engine Stamp</span>
              </div>
            </div>
          </div>

          {/* Weekday Column Headers */}
          <div className="grid grid-cols-7 gap-1 sm:gap-2 text-center text-xs font-semibold text-slate-400 dark:text-slate-500 py-3 border-b border-slate-100 dark:border-slate-800">
            <span className="hidden sm:inline">Sunday</span>
            <span className="sm:hidden">Sun</span>
            <span className="hidden sm:inline">Monday</span>
            <span className="sm:hidden">Mon</span>
            <span className="hidden sm:inline">Tuesday</span>
            <span className="sm:hidden">Tue</span>
            <span className="hidden sm:inline">Wednesday</span>
            <span className="sm:hidden">Wed</span>
            <span className="hidden sm:inline">Thursday</span>
            <span className="sm:hidden">Thu</span>
            <span className="hidden sm:inline">Friday</span>
            <span className="sm:hidden">Fri</span>
            <span className="hidden sm:inline">Saturday</span>
            <span className="sm:hidden">Sat</span>
          </div>

          {/* Calendar Grid Cells */}
          <div className="grid grid-cols-7 gap-1 sm:gap-2 pt-2">
            {calendarDays.map((day, idx) => {
              const hasEntries = day.entries.length > 0;
              const dayIncomes = day.entries.filter((e) => e.type === 'income');
              const dayExpenses = day.entries.filter((e) => e.type === 'expense');

              return (
                <div
                  key={`${day.dateString}-${idx}`}
                  onClick={() => {
                    if (hasEntries) {
                      setSelectedDateDetails(day.dateString);
                    }
                  }}
                  className={`min-h-[90px] sm:min-h-[110px] rounded-xl border p-1.5 sm:p-2 transition flex flex-col justify-between ${
                    day.isCurrentMonth
                      ? hasEntries
                        ? 'border-indigo-200 bg-indigo-50/20 hover:border-indigo-400 hover:bg-indigo-50/40 dark:border-indigo-900/60 dark:bg-indigo-950/20 cursor-pointer'
                        : 'border-slate-200/70 bg-white hover:bg-slate-50 dark:border-slate-800 dark:bg-slate-900/50 dark:hover:bg-slate-800/40'
                      : 'border-transparent bg-slate-50/40 text-slate-300 dark:bg-slate-900/20 dark:text-slate-700 pointer-events-none'
                  } ${day.isToday ? 'ring-2 ring-indigo-500' : ''}`}
                >
                  {/* Day Header */}
                  <div className="flex items-center justify-between">
                    <span
                      className={`text-xs font-bold rounded-md px-1.5 py-0.5 ${
                        day.isToday
                          ? 'bg-indigo-600 text-white'
                          : day.isCurrentMonth
                          ? 'text-slate-800 dark:text-slate-200'
                          : 'text-slate-400 dark:text-slate-600'
                      }`}
                    >
                      {day.dayNumber}
                    </span>

                    {/* Day Balance Mini Indicator */}
                    {hasEntries && (
                      <span className="text-[10px] font-semibold text-slate-500 dark:text-slate-400 hidden sm:inline">
                        {day.entries.length} {day.entries.length === 1 ? 'item' : 'items'}
                      </span>
                    )}
                  </div>

                  {/* Day Entry Chips */}
                  <div className="space-y-1 my-1 flex-1 overflow-hidden">
                    {day.entries.slice(0, 3).map((entry) => {
                      const isIncome = entry.type === 'income';
                      const isPending = entry.status === 'pending-scheduled';

                      return (
                        <div
                          key={entry.id}
                          onClick={(e) => {
                            e.stopPropagation();
                            setSelectedEntry(entry);
                          }}
                          className={`group text-left px-1.5 py-0.5 rounded text-[10px] font-medium leading-tight truncate transition cursor-pointer flex items-center justify-between gap-1 ${
                            isPending
                              ? 'border border-dashed border-indigo-400 bg-indigo-50/80 text-indigo-800 dark:border-indigo-600 dark:bg-indigo-950/60 dark:text-indigo-200'
                              : isIncome
                              ? 'bg-emerald-50 text-emerald-800 hover:bg-emerald-100 border border-emerald-200/80 dark:bg-emerald-950/60 dark:text-emerald-300 dark:border-emerald-800'
                              : 'bg-rose-50 text-rose-800 hover:bg-rose-100 border border-rose-200/80 dark:bg-rose-950/60 dark:text-rose-300 dark:border-rose-800'
                          }`}
                          title={`${entry.title}: ${formatPKR(entry.amount)} (${entry.status})`}
                        >
                          <div className="flex items-center gap-1 min-w-0 truncate">
                            {isPending ? (
                              <Clock className="h-2.5 w-2.5 shrink-0 text-indigo-500" />
                            ) : entry.status === 'auto-generated' ? (
                              <Zap className="h-2.5 w-2.5 shrink-0 text-amber-500" />
                            ) : (
                              <Repeat className="h-2.5 w-2.5 shrink-0 text-slate-400" />
                            )}
                            <span className="truncate">{entry.title}</span>
                          </div>
                          <span className="shrink-0 font-bold ml-1 text-[9px]">
                            {isIncome ? '+' : '-'}
                            {formatPKR(entry.amount, true)}
                          </span>
                        </div>
                      );
                    })}

                    {/* Overflow Badge */}
                    {day.entries.length > 3 && (
                      <div className="text-[9px] font-semibold text-indigo-600 dark:text-indigo-400 text-center hover:underline">
                        +{day.entries.length - 3} more items
                      </div>
                    )}
                  </div>

                  {/* Day Footer Summary */}
                  {hasEntries && (
                    <div className="pt-0.5 border-t border-slate-100 dark:border-slate-800 text-[9px] font-bold flex items-center justify-between text-slate-400">
                      {dayIncomes.length > 0 && (
                        <span className="text-emerald-600 dark:text-emerald-400 truncate">
                          +{formatPKR(dayIncomes.reduce((s, i) => s + i.amount, 0), true)}
                        </span>
                      )}
                      {dayExpenses.length > 0 && (
                        <span className="text-rose-600 dark:text-rose-400 truncate ml-auto">
                          -{formatPKR(dayExpenses.reduce((s, e) => s + e.amount, 0), true)}
                        </span>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Alternative View: Audit Ledger Mode */}
      {viewMode === 'audit' && (
        <div className="rounded-2xl border border-slate-200 bg-white shadow-xs dark:border-slate-800 dark:bg-slate-900 overflow-hidden">
          <div className="p-4 sm:p-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
            <div>
              <h2 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <span>Automated Entries Verification Ledger</span>
                <span className="rounded-full bg-slate-100 dark:bg-slate-800 px-2 py-0.5 text-xs text-slate-600 dark:text-slate-300">
                  {filteredEntries.length} Records
                </span>
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                Chronological list of all automatically generated and rule-based entries for verification
              </p>
            </div>
          </div>

          {filteredEntries.length === 0 ? (
            <div className="p-8 text-center">
              <Info className="h-8 w-8 text-slate-400 mx-auto mb-2" />
              <p className="text-sm font-medium text-slate-600 dark:text-slate-300">
                No recurring automation entries found matching the selected filter.
              </p>
              <p className="text-xs text-slate-400 mt-1">
                Try selecting "All Statuses" or navigating to another month.
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead className="bg-slate-50 dark:bg-slate-800/60 text-slate-500 dark:text-slate-400 border-b border-slate-200 dark:border-slate-800">
                  <tr>
                    <th className="py-3 px-4 font-semibold">Date</th>
                    <th className="py-3 px-4 font-semibold">Type</th>
                    <th className="py-3 px-4 font-semibold">Source / Category</th>
                    <th className="py-3 px-4 font-semibold">Amount (PKR)</th>
                    <th className="py-3 px-4 font-semibold">Automation Status</th>
                    <th className="py-3 px-4 font-semibold">Cadence</th>
                    <th className="py-3 px-4 font-semibold">Processed Timestamp</th>
                    <th className="py-3 px-4 font-semibold">Notes</th>
                    <th className="py-3 px-4 font-semibold text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {filteredEntries.map((entry) => {
                    const isIncome = entry.type === 'income';
                    const isPending = entry.status === 'pending-scheduled';

                    return (
                      <tr
                        key={entry.id}
                        className="hover:bg-slate-50/80 dark:hover:bg-slate-800/40 transition"
                      >
                        <td className="py-3 px-4 font-medium whitespace-nowrap text-slate-900 dark:text-slate-100">
                          {formatDate(entry.date)}
                        </td>
                        <td className="py-3 px-4 whitespace-nowrap">
                          <span
                            className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-semibold ${
                              isIncome
                                ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300'
                                : 'bg-rose-100 text-rose-800 dark:bg-rose-950 dark:text-rose-300'
                            }`}
                          >
                            {isIncome ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}
                            {isIncome ? 'Inflow' : 'Outflow'}
                          </span>
                        </td>
                        <td className="py-3 px-4 font-bold text-slate-900 dark:text-slate-100 whitespace-nowrap">
                          {entry.title}
                        </td>
                        <td
                          className={`py-3 px-4 font-bold whitespace-nowrap ${
                            isIncome
                              ? 'text-emerald-600 dark:text-emerald-400'
                              : 'text-rose-600 dark:text-rose-400'
                          }`}
                        >
                          {isIncome ? '+' : '-'} {formatPKR(entry.amount)}
                        </td>
                        <td className="py-3 px-4 whitespace-nowrap">
                          {entry.status === 'auto-generated' && (
                            <span className="inline-flex items-center gap-1 rounded-md bg-amber-50 px-2 py-0.5 text-[11px] font-medium text-amber-800 border border-amber-200 dark:bg-amber-950/80 dark:text-amber-300 dark:border-amber-800">
                              <Zap className="h-3 w-3 text-amber-500" />
                              Auto-Generated
                            </span>
                          )}
                          {entry.status === 'template-rule' && (
                            <span className="inline-flex items-center gap-1 rounded-md bg-blue-50 px-2 py-0.5 text-[11px] font-medium text-blue-800 border border-blue-200 dark:bg-blue-950/80 dark:text-blue-300 dark:border-blue-800">
                              <Repeat className="h-3 w-3 text-blue-500" />
                              Rule Template
                            </span>
                          )}
                          {entry.status === 'pending-scheduled' && (
                            <span className="inline-flex items-center gap-1 rounded-md bg-indigo-50 px-2 py-0.5 text-[11px] font-medium text-indigo-800 border border-indigo-200 dark:bg-indigo-950/80 dark:text-indigo-300 dark:border-indigo-800">
                              <Clock className="h-3 w-3 text-indigo-500" />
                              Scheduled Pending
                            </span>
                          )}
                        </td>
                        <td className="py-3 px-4 whitespace-nowrap capitalize text-slate-500 dark:text-slate-400">
                          {entry.frequency}
                        </td>
                        <td className="py-3 px-4 whitespace-nowrap text-slate-400 text-[11px]">
                          {entry.createdAt ? new Date(entry.createdAt).toLocaleString() : 'Template Record'}
                        </td>
                        <td className="py-3 px-4 max-w-[200px] truncate text-slate-500 dark:text-slate-400">
                          {entry.notes || '—'}
                        </td>
                        <td className="py-3 px-4 text-right whitespace-nowrap">
                          <div className="flex items-center justify-end gap-1.5">
                            <button
                              onClick={() => setSelectedEntry(entry)}
                              className="rounded-lg border border-slate-200 px-2.5 py-1 text-slate-600 hover:bg-slate-100 hover:text-slate-900 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800 transition"
                            >
                              Verify
                            </button>
                            {!isPending && (
                              <button
                                onClick={() => handleDeleteEntry(entry)}
                                className="rounded-lg p-1 text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-950 dark:hover:text-rose-400 transition"
                                title="Remove this automated entry"
                              >
                                <Trash2 className="h-3.5 w-3.5" />
                              </button>
                            )}
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* Active Recurring Rules Reference Strip */}
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs dark:border-slate-800 dark:bg-slate-900">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-4">
          <div>
            <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <Repeat className="h-4 w-4 text-indigo-600 dark:text-indigo-400" />
              <span>Configured Recurring Rules Registry</span>
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Source rules defined across your Income and Expense modules that trigger this calendar automation
            </p>
          </div>
          <div className="flex items-center gap-2">
            {onNavigateToIncome && (
              <button
                onClick={onNavigateToIncome}
                className="text-xs text-indigo-600 dark:text-indigo-400 hover:underline flex items-center gap-1 font-medium"
              >
                <span>Manage Incomes</span>
                <ArrowRight className="h-3 w-3" />
              </button>
            )}
            <span className="text-slate-300 dark:text-slate-700">•</span>
            {onNavigateToExpense && (
              <button
                onClick={onNavigateToExpense}
                className="text-xs text-indigo-600 dark:text-indigo-400 hover:underline flex items-center gap-1 font-medium"
              >
                <span>Manage Expenses</span>
                <ArrowRight className="h-3 w-3" />
              </button>
            )}
          </div>
        </div>

        {/* Rule Badges */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
          {/* Income Templates */}
          {state.incomes
            .filter((i) => i.isRecurring && !i.autoGeneratedFromId)
            .map((rule) => (
              <div
                key={rule.id}
                className="rounded-xl border border-emerald-200 bg-emerald-50/50 p-3 dark:border-emerald-900/60 dark:bg-emerald-950/20"
              >
                <div className="flex items-start justify-between">
                  <span className="rounded-md bg-emerald-100 px-2 py-0.5 text-[10px] font-bold text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200 uppercase">
                    Income Rule
                  </span>
                  <span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300 capitalize">
                    {rule.recurringFrequency || 'monthly'}
                  </span>
                </div>
                <div className="mt-2 text-xs font-bold text-slate-900 dark:text-white truncate">
                  {rule.source}
                </div>
                <div className="text-sm font-bold text-emerald-600 dark:text-emerald-400 mt-0.5">
                  +{formatPKR(rule.amount)}
                </div>
                <div className="mt-1 text-[10px] text-slate-500 dark:text-slate-400">
                  Repeats: Day {rule.date.split('-')[2] || '01'} of cycle
                </div>
              </div>
            ))}

          {/* Expense Templates */}
          {state.expenses
            .filter((e) => e.isRecurring && !e.autoGeneratedFromId)
            .map((rule) => (
              <div
                key={rule.id}
                className="rounded-xl border border-rose-200 bg-rose-50/50 p-3 dark:border-rose-900/60 dark:bg-rose-950/20"
              >
                <div className="flex items-start justify-between">
                  <span className="rounded-md bg-rose-100 px-2 py-0.5 text-[10px] font-bold text-rose-800 dark:bg-rose-900 dark:text-rose-200 uppercase">
                    Expense Rule
                  </span>
                  <span className="text-[10px] font-semibold text-rose-700 dark:text-rose-300 capitalize">
                    {rule.recurringFrequency || 'monthly'}
                  </span>
                </div>
                <div className="mt-2 text-xs font-bold text-slate-900 dark:text-white truncate">
                  {rule.category}
                </div>
                <div className="text-sm font-bold text-rose-600 dark:text-rose-400 mt-0.5">
                  -{formatPKR(rule.amount)}
                </div>
                <div className="mt-1 text-[10px] text-slate-500 dark:text-slate-400 truncate">
                  {rule.notes || `Day ${rule.date.split('-')[2] || '01'} of cycle`}
                </div>
              </div>
            ))}
        </div>
      </div>

      {/* Date Details Modal (When user clicks on a calendar day) */}
      {selectedDateDetails && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4 backdrop-blur-xs">
          <div className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-5 shadow-xl dark:border-slate-800 dark:bg-slate-900 animate-in fade-in zoom-in-95">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-slate-800">
              <div className="flex items-center gap-2">
                <CalendarIcon className="h-5 w-5 text-indigo-600" />
                <h3 className="font-bold text-base text-slate-900 dark:text-white">
                  Schedule for {formatDate(selectedDateDetails)}
                </h3>
              </div>
              <button
                onClick={() => setSelectedDateDetails(null)}
                className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600 dark:hover:bg-slate-800"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="py-4 space-y-3 max-h-[60vh] overflow-y-auto">
              {dateEntriesForModal.length === 0 ? (
                <p className="text-xs text-slate-400 text-center py-4">
                  No automated entries for this date.
                </p>
              ) : (
                dateEntriesForModal.map((entry) => {
                  const isIncome = entry.type === 'income';
                  const isPending = entry.status === 'pending-scheduled';

                  return (
                    <div
                      key={entry.id}
                      className="rounded-xl border border-slate-200 bg-slate-50/50 p-3.5 dark:border-slate-800 dark:bg-slate-800/50"
                    >
                      <div className="flex items-start justify-between">
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="font-bold text-sm text-slate-900 dark:text-white">
                              {entry.title}
                            </span>
                            {entry.status === 'auto-generated' && (
                              <span className="inline-flex items-center gap-0.5 rounded bg-amber-100 px-1.5 py-0.5 text-[9px] font-bold text-amber-800 dark:bg-amber-950 dark:text-amber-300">
                                <Zap className="h-2.5 w-2.5" /> Auto-Generated
                              </span>
                            )}
                            {entry.status === 'template-rule' && (
                              <span className="inline-flex items-center gap-0.5 rounded bg-blue-100 px-1.5 py-0.5 text-[9px] font-bold text-blue-800 dark:bg-blue-950 dark:text-blue-300">
                                <Repeat className="h-2.5 w-2.5" /> Rule Template
                              </span>
                            )}
                            {isPending && (
                              <span className="inline-flex items-center gap-0.5 rounded bg-indigo-100 px-1.5 py-0.5 text-[9px] font-bold text-indigo-800 dark:bg-indigo-950 dark:text-indigo-300">
                                <Clock className="h-2.5 w-2.5" /> Pending Run
                              </span>
                            )}
                          </div>
                          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                            {entry.notes || `${entry.frequency} recurring commitment`}
                          </p>
                        </div>
                        <div
                          className={`text-base font-bold ${
                            isIncome
                              ? 'text-emerald-600 dark:text-emerald-400'
                              : 'text-rose-600 dark:text-rose-400'
                          }`}
                        >
                          {isIncome ? '+' : '-'} {formatPKR(entry.amount)}
                        </div>
                      </div>

                      <div className="mt-3 flex items-center justify-between pt-2 border-t border-slate-200/60 dark:border-slate-700/60 text-xs">
                        <span className="text-[11px] text-slate-400 capitalize">
                          Frequency: {entry.frequency}
                        </span>
                        <div className="flex items-center gap-2">
                          <button
                            onClick={() => {
                              setSelectedDateDetails(null);
                              setSelectedEntry(entry);
                            }}
                            className="text-xs text-indigo-600 dark:text-indigo-400 font-medium hover:underline"
                          >
                            Inspect Audit Record
                          </button>
                          {!isPending && (
                            <button
                              onClick={() => handleDeleteEntry(entry)}
                              className="text-xs text-rose-600 hover:text-rose-700 font-medium"
                            >
                              Delete
                            </button>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })
              )}
            </div>

            <div className="flex justify-end pt-3 border-t border-slate-100 dark:border-slate-800">
              <button
                onClick={() => setSelectedDateDetails(null)}
                className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Entry Audit & Verification Modal */}
      {selectedEntry && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4 backdrop-blur-xs">
          <div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-5 shadow-xl dark:border-slate-800 dark:bg-slate-900 animate-in fade-in zoom-in-95">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-slate-800">
              <div className="flex items-center gap-2">
                <ShieldCheck className="h-5 w-5 text-indigo-600 dark:text-indigo-400" />
                <h3 className="font-bold text-base text-slate-900 dark:text-white">
                  Automation Verification Record
                </h3>
              </div>
              <button
                onClick={() => setSelectedEntry(null)}
                className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600 dark:hover:bg-slate-800"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="py-4 space-y-4 text-xs">
              {/* Status Header Pill */}
              <div className="rounded-xl border border-slate-200 bg-slate-50 p-3.5 dark:border-slate-800 dark:bg-slate-800/60">
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
                    {selectedEntry.type === 'income' ? 'Income Transaction' : 'Expense Commitment'}
                  </span>
                  {selectedEntry.status === 'auto-generated' && (
                    <span className="rounded-full bg-amber-100 px-2.5 py-0.5 text-[10px] font-bold text-amber-800 dark:bg-amber-950 dark:text-amber-300 flex items-center gap-1">
                      <Zap className="h-3 w-3" /> Auto-Generated Instance
                    </span>
                  )}
                  {selectedEntry.status === 'template-rule' && (
                    <span className="rounded-full bg-blue-100 px-2.5 py-0.5 text-[10px] font-bold text-blue-800 dark:bg-blue-950 dark:text-blue-300 flex items-center gap-1">
                      <Repeat className="h-3 w-3" /> Base Rule Template
                    </span>
                  )}
                  {selectedEntry.status === 'pending-scheduled' && (
                    <span className="rounded-full bg-indigo-100 px-2.5 py-0.5 text-[10px] font-bold text-indigo-800 dark:bg-indigo-950 dark:text-indigo-300 flex items-center gap-1">
                      <Clock className="h-3 w-3" /> Scheduled Pending
                    </span>
                  )}
                </div>

                <div className="flex items-baseline justify-between mt-2">
                  <h4 className="text-lg font-bold text-slate-900 dark:text-white">
                    {selectedEntry.title}
                  </h4>
                  <span
                    className={`text-lg font-extrabold ${
                      selectedEntry.type === 'income'
                        ? 'text-emerald-600 dark:text-emerald-400'
                        : 'text-rose-600 dark:text-rose-400'
                    }`}
                  >
                    {selectedEntry.type === 'income' ? '+' : '-'} {formatPKR(selectedEntry.amount)}
                  </span>
                </div>
              </div>

              {/* Data Specifications Grid */}
              <div className="space-y-2 rounded-xl border border-slate-200 bg-white p-3.5 dark:border-slate-800 dark:bg-slate-900">
                <div className="flex justify-between py-1 border-b border-slate-100 dark:border-slate-800">
                  <span className="text-slate-400">Scheduled Execution Date:</span>
                  <span className="font-semibold text-slate-900 dark:text-white">
                    {formatDate(selectedEntry.date)} ({selectedEntry.date})
                  </span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-100 dark:border-slate-800">
                  <span className="text-slate-400">Repetition Cadence:</span>
                  <span className="font-semibold capitalize text-slate-900 dark:text-white">
                    {selectedEntry.frequency}
                  </span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-100 dark:border-slate-800">
                  <span className="text-slate-400">System Record ID:</span>
                  <span className="font-mono text-[10px] text-slate-600 dark:text-slate-300">
                    {selectedEntry.id}
                  </span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-100 dark:border-slate-800">
                  <span className="text-slate-400">Source Rule Reference:</span>
                  <span className="font-mono text-[10px] text-indigo-600 dark:text-indigo-400">
                    {selectedEntry.sourceTemplateId || selectedEntry.autoGeneratedFromId || 'Direct Rule Template'}
                  </span>
                </div>
                <div className="flex justify-between py-1">
                  <span className="text-slate-400">Processed Timestamp:</span>
                  <span className="text-slate-700 dark:text-slate-300">
                    {selectedEntry.createdAt
                      ? new Date(selectedEntry.createdAt).toLocaleString()
                      : 'Scheduled (Not Yet Processed)'}
                  </span>
                </div>
              </div>

              {/* Notes */}
              {selectedEntry.notes && (
                <div className="rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-800">
                  <span className="font-semibold text-slate-500 dark:text-slate-400">
                    System Notes & Description:
                  </span>
                  <p className="mt-1 text-slate-700 dark:text-slate-300">
                    {selectedEntry.notes}
                  </p>
                </div>
              )}
            </div>

            {/* Modal Actions */}
            <div className="flex items-center justify-between pt-3 border-t border-slate-100 dark:border-slate-800">
              {selectedEntry.status !== 'pending-scheduled' ? (
                <button
                  onClick={() => handleDeleteEntry(selectedEntry)}
                  className="inline-flex items-center gap-1.5 rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700 hover:bg-rose-100 dark:border-rose-900/60 dark:bg-rose-950/40 dark:text-rose-300 transition"
                >
                  <Trash2 className="h-3.5 w-3.5" />
                  <span>Rollback / Remove Entry</span>
                </button>
              ) : (
                <div />
              )}
              <button
                onClick={() => setSelectedEntry(null)}
                className="rounded-xl bg-slate-900 px-4 py-2 text-xs font-semibold text-white hover:bg-slate-800 dark:bg-white dark:text-slate-900 dark:hover:bg-slate-100 transition"
              >
                Close Verification
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
