import { AppState, IncomeItem, ExpenseItem, RecurringFrequency } from '../types/finance';

// Helper to get number of days in a year-month string (YYYY-MM)
export function getDaysInMonth(yearMonth: string): number {
  const [yearStr, monthStr] = yearMonth.split('-');
  const year = parseInt(yearStr, 10);
  const month = parseInt(monthStr, 10);
  return new Date(year, month, 0).getDate();
}

// Clamps day of month to valid range for target month
export function clampDayToMonth(yearMonth: string, day: number): number {
  const maxDays = getDaysInMonth(yearMonth);
  return Math.min(Math.max(1, day), maxDays);
}

// Computes approximate monthly cost/income impact for statistics
export function getNormalizedMonthlyAmount(amount: number, frequency: RecurringFrequency): number {
  switch (frequency) {
    case 'weekly':
      return Math.round(amount * 4.333);
    case 'monthly':
      return amount;
    case 'yearly':
      return Math.round(amount / 12);
    default:
      return amount;
  }
}

// Find all distinct recurring source templates (items where isRecurring is true)
export function getRecurringIncomes(incomes: IncomeItem[]): IncomeItem[] {
  // Return items with isRecurring flag
  return incomes.filter((i) => i.isRecurring && !i.autoGeneratedFromId);
}

export function getRecurringExpenses(expenses: ExpenseItem[]): ExpenseItem[] {
  return expenses.filter((e) => e.isRecurring && !e.autoGeneratedFromId);
}

// Calculate summary stats of recurring commitments
export function getRecurringSummary(incomes: IncomeItem[], expenses: ExpenseItem[]) {
  const recIncomes = incomes.filter((i) => i.isRecurring);
  const recExpenses = expenses.filter((e) => e.isRecurring);

  const monthlyRecIncome = recIncomes.reduce(
    (sum, i) => sum + getNormalizedMonthlyAmount(i.amount, i.recurringFrequency || 'monthly'),
    0
  );

  const monthlyRecExpense = recExpenses.reduce(
    (sum, e) => sum + getNormalizedMonthlyAmount(e.amount, e.recurringFrequency || 'monthly'),
    0
  );

  return {
    recurringIncomeCount: recIncomes.length,
    recurringExpenseCount: recExpenses.length,
    monthlyRecIncome,
    monthlyRecExpense,
    netRecurringFlow: monthlyRecIncome - monthlyRecExpense,
  };
}

// Generate candidate date strings for a recurring item in a target month
export function getCandidateDatesForMonth(
  itemDate: string,
  frequency: RecurringFrequency,
  targetMonth: string
): string[] {
  const [origYear, origMonth, origDayStr] = itemDate.split('-');
  const origDay = parseInt(origDayStr || '1', 10);

  if (frequency === 'monthly') {
    const clampedDay = clampDayToMonth(targetMonth, origDay);
    const dayPadded = String(clampedDay).padStart(2, '0');
    return [`${targetMonth}-${dayPadded}`];
  }

  if (frequency === 'yearly') {
    // Only applies if targetMonth has the same month number as original item
    const [, targetMonthNum] = targetMonth.split('-');
    if (origMonth === targetMonthNum) {
      const clampedDay = clampDayToMonth(targetMonth, origDay);
      const dayPadded = String(clampedDay).padStart(2, '0');
      return [`${targetMonth}-${dayPadded}`];
    }
    return [];
  }

  if (frequency === 'weekly') {
    // Find all days in targetMonth that share the same day-of-the-week as origDate
    const origDateObj = new Date(parseInt(origYear, 10), parseInt(origMonth, 10) - 1, origDay);
    const targetDayOfWeek = origDateObj.getDay();

    const [tYear, tMonth] = targetMonth.split('-');
    const maxDays = getDaysInMonth(targetMonth);
    const dates: string[] = [];

    for (let day = 1; day <= maxDays; day++) {
      const d = new Date(parseInt(tYear, 10), parseInt(tMonth, 10) - 1, day);
      if (d.getDay() === targetDayOfWeek) {
        dates.push(`${targetMonth}-${String(day).padStart(2, '0')}`);
      }
    }
    return dates;
  }

  return [];
}

export interface PendingRecurringGeneration {
  pendingIncomes: Array<Omit<IncomeItem, 'id' | 'createdAt'> & { sourceTemplateId: string }>;
  pendingExpenses: Array<Omit<ExpenseItem, 'id' | 'createdAt'> & { sourceTemplateId: string }>;
  totalCount: number;
}

// Detect recurring entries that should exist in targetMonth but aren't present yet
export function detectPendingRecurring(
  state: AppState,
  targetMonth: string
): PendingRecurringGeneration {
  const pendingIncomes: Array<Omit<IncomeItem, 'id' | 'createdAt'> & { sourceTemplateId: string }> = [];
  const pendingExpenses: Array<Omit<ExpenseItem, 'id' | 'createdAt'> & { sourceTemplateId: string }> = [];

  // 1. Process recurring incomes
  // Distinct recurring source templates
  const recurringIncomes = state.incomes.filter((i) => i.isRecurring && !i.autoGeneratedFromId);

  recurringIncomes.forEach((rec) => {
    const freq = rec.recurringFrequency || 'monthly';
    const candidateDates = getCandidateDatesForMonth(rec.date, freq, targetMonth);

    candidateDates.forEach((candDate) => {
      // Don't duplicate if this exact item was created on this date
      if (rec.date === candDate) return;

      // Check if an entry already exists for this template on this date or targetMonth
      const alreadyExists = state.incomes.some(
        (i) =>
          (i.autoGeneratedFromId === rec.id && i.date === candDate) ||
          (i.source === rec.source && i.amount === rec.amount && i.date === candDate)
      );

      if (!alreadyExists) {
        pendingIncomes.push({
          source: rec.source,
          amount: rec.amount,
          date: candDate,
          notes: rec.notes ? `${rec.notes} (Recurring ${freq})` : `Recurring ${freq} income`,
          isRecurring: true,
          recurringFrequency: freq,
          autoGeneratedFromId: rec.id,
          sourceTemplateId: rec.id,
        });
      }
    });
  });

  // 2. Process recurring expenses
  const recurringExpenses = state.expenses.filter((e) => e.isRecurring && !e.autoGeneratedFromId);

  recurringExpenses.forEach((rec) => {
    const freq = rec.recurringFrequency || 'monthly';
    const candidateDates = getCandidateDatesForMonth(rec.date, freq, targetMonth);

    candidateDates.forEach((candDate) => {
      if (rec.date === candDate) return;

      const alreadyExists = state.expenses.some(
        (e) =>
          (e.autoGeneratedFromId === rec.id && e.date === candDate) ||
          (e.category === rec.category && e.amount === rec.amount && e.date === candDate)
      );

      if (!alreadyExists) {
        pendingExpenses.push({
          category: rec.category,
          type: rec.type,
          amount: rec.amount,
          date: candDate,
          notes: rec.notes ? `${rec.notes} (Recurring ${freq})` : `Recurring ${freq} expense`,
          isRecurring: true,
          recurringFrequency: freq,
          autoGeneratedFromId: rec.id,
          sourceTemplateId: rec.id,
        });
      }
    });
  });

  return {
    pendingIncomes,
    pendingExpenses,
    totalCount: pendingIncomes.length + pendingExpenses.length,
  };
}
